# Generated by Django 4.2 on 2024-04-09 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='caterory',
            new_name='category',
        ),
    ]
